# Generated by Django 5.2.6 on 2026-03-06 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('prenom_nom', models.CharField(max_length=200, verbose_name='Prénom et Nom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField(verbose_name='Adresse de livraison')),
                ('mode_paiement', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN MoMo'), ('livraison', 'Paiement à la livraison'), ('virement', 'Virement bancaire')], max_length=20, verbose_name='Mode de paiement')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / Instructions')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='nouvelle', max_length=20)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('mode', 'Mode'), ('accessoires', 'Accessoires'), ('maison', 'Maison')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=12)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('image_url', models.URLField(blank=True, help_text="URL externe de l'image (si pas d'upload)", null=True)),
                ('badge', models.CharField(blank=True, choices=[('', 'Aucun'), ('Nouveau', 'Nouveau'), ('Bestseller', 'Bestseller'), ('Exclusif', 'Exclusif'), ('Premium', 'Premium')], default='', max_length=20)),
                ('note', models.IntegerField(choices=[(1, '1 étoile(s)'), (2, '2 étoile(s)'), (3, '3 étoile(s)'), (4, '4 étoile(s)'), (5, '5 étoile(s)')], default=5)),
                ('stock', models.IntegerField(default=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=200)),
                ('prix_unitaire', models.DecimalField(decimal_places=0, max_digits=12)),
                ('quantite', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boutique.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.product')),
            ],
            options={
                'verbose_name': 'Article commandé',
                'verbose_name_plural': 'Articles commandés',
            },
        ),
    ]
