# Generated by Django 5.2.6 on 2026-03-12 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_vendor_user_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prix_achat',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name="Prix d'achat"),
        ),
        migrations.AddField(
            model_name='product',
            name='seuil_alerte_stock',
            field=models.IntegerField(default=3, verbose_name="Seuil d'alerte stock"),
        ),
        migrations.CreateModel(
            name='OfflineSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=200)),
                ('quantite', models.IntegerField(default=1)),
                ('prix_vente', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Prix de vente unitaire')),
                ('prix_achat', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name="Prix d'achat unitaire")),
                ('client_nom', models.CharField(blank=True, max_length=200, verbose_name='Nom du client')),
                ('client_telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du client')),
                ('notes', models.TextField(blank=True)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_sales', to='boutique.product')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_sales', to='boutique.vendor')),
            ],
            options={
                'verbose_name': 'Vente hors site',
                'verbose_name_plural': 'Ventes hors site',
                'ordering': ['-date_vente'],
            },
        ),
    ]
