# Generated by Django 5.2.6 on 2026-03-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_comptabilite_vendeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorie',
            field=models.CharField(choices=[('agricole', 'Produits agricoles'), ('fruits', 'Fruits et légumes'), ('electronique', 'Électronique'), ('mode', 'Mode et habillement'), ('maison', 'Maison et décoration'), ('beaute', 'Beauté et bien-être'), ('artisanat', 'Artisanat local'), ('restaurant', 'Restaurant'), ('services', 'Services et autres')], max_length=20),
        ),
    ]
