# Generated by Django 5.2.6 on 2026-03-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0006_alter_product_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='actif',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorie',
            field=models.CharField(choices=[('agricole', 'Produits agricoles'), ('fruits', 'Fruits et légumes'), ('electronique', 'Électronique'), ('mode', 'Mode et habillement'), ('maison', 'Maison et décoration'), ('beaute', 'Beauté et bien-être'), ('artisanat', 'Artisanat local'), ('restaurant', 'Restaurant'), ('services', 'Services et autres')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_vente',
            field=models.CharField(choices=[('detail', 'Détail'), ('grossiste', 'Grossiste')], db_index=True, default='detail', max_length=20),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['actif', 'categorie'], name='boutique_pr_actif_64005b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['actif', '-date_ajout'], name='boutique_pr_actif_4f614b_idx'),
        ),
    ]
